package id.ac.uty.mykade.model

data class Event (
    var idEvent: String? = null,
    var idSoccerXML: String?,
    var strEvent: String?,
    var strFilename: String?,
    var strSport: String?,
    var idLeague: String?,
    var strLeague: String?,
    var strSeason: String?,
    var strDescriptionEN: String?,
    var strHomeTeam: String? = null,
    var strAwayTeam: String? = null,
    var intHomeScore: String? = null,
    var intRound: String?,
    var intAwayScore: String? = null,
    var intSpectators: String?,
    var strHomeGoalDetails: String?,
    var strHomeRedCards: String?,
    var strHomeYellowCards: String?,
    var strHomeLineupGoalkeeper: String?,
    var strHomeLineupDefense: String?,
    var strHomeLineupMidfield: String?,
    var strHomeLineupForward: String?,
    var strHomeLineupSubstitutes: String?,
    var strHomeFormation: String?,
    var strAwayRedCards: String?,
    var strAwayYellowCards: String?,
    var strAwayGoalDetails: String?,
    var strAwayLineupGoalkeeper: String?,
    var strAwayLineupDefense: String?,
    var strAwayLineupMidfield: String?,
    var strAwayLineupForward: String?,
    var strAwayLineupSubstitutes: String?,
    var strAwayFormation: String?,
    var intHomeShots: String?,
    var intAwayShots: String?,
    var dateEvent: String? = null,
    var strDate: String?,
    var strTime: String?,
    var strTVStation: String?,
    var idHomeTeam: String?,
    var idAwayTeam: String?,
    var strResult: String?,
    var strCircuit: String?,
    var strCountry: String?,
    var strCity: String?,
    var strPoster: String?,
    var strFanart: String?,
    var strThumb: String?,
    var strBanner: String?,
    var strMap: String?,
    var strLocked: String?
)
